# Generated by Django 2.2 on 2020-05-06 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InputDataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inputFile', models.FileField(upload_to='student_notes/')),
                ('fileUse', models.CharField(choices=[('', '-------'), ('train', 'Model Training'), ('test', 'Model Testing')], default=' ', max_length=50)),
            ],
        ),
    ]
