# Generated by Django 2.2 on 2020-05-12 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputdataset',
            name='rankingMethod',
            field=models.CharField(choices=[('', '-------'), ('lambdaMart', 'LambdaMart')], default=' ', max_length=50),
        ),
        migrations.AlterField(
            model_name='inputdataset',
            name='fileUse',
            field=models.CharField(choices=[('', '-------'), ('train', 'Model Training'), ('test', 'Model Testing'), ('validate', 'Model Validation')], default=' ', max_length=50),
        ),
        migrations.AlterField(
            model_name='inputdataset',
            name='inputFile',
            field=models.FileField(upload_to='uploadedFiles/'),
        ),
    ]
